M48
; DRILL file {KiCad 7.0.1} date Wed Apr 12 13:53:48 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-12T13:53:48+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X22.575Y80.72
X27.425Y80.72
T2
X22.275Y83.75
X27.725Y83.75
T3
X3.0Y83.0
X3.0Y6.92
X47.0Y83.0
X47.0Y6.92
T0
M30
