M48
; DRILL file {KiCad 7.0.1} date Wed Apr 12 14:45:32 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-12T14:45:32+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X5.45Y23.0
X8.5Y23.0
T2
X9.475Y2.825
X12.015Y2.825
T0
M30
