M48
; DRILL file {KiCad 7.0.1} date Wed Apr 12 14:45:32 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-12T14:45:32+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X18.0Y24.0
X21.5Y29.0
X21.5Y19.0
X25.0Y24.0
X28.5Y29.0
X28.5Y19.0
X32.0Y24.0
T2
X3.0Y83.0
X3.0Y6.92
X47.0Y83.0
X47.0Y6.92
T0
M30
